create table if not exists public.settings (
  id integer primary key,
  base_fare numeric(10,2) not null default 12.00,
  price_per_km numeric(10,2) not null default 1.50,
  minimum_fare numeric(10,2) not null default 15.00,
  dispatch_mode text not null default 'auto' check (dispatch_mode in ('auto', 'manual')),
  service_status boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('fixed', 'percent')),
  discount_value numeric(10,2) not null check (discount_value >= 0),
  expiry_date timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.settings (id, base_fare, price_per_km, minimum_fare, dispatch_mode, service_status)
values (1, 12.00, 1.50, 15.00, 'auto', true)
on conflict (id) do nothing;

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
before update on public.settings
for each row
execute function public.set_updated_at();

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at
before update on public.coupons
for each row
execute function public.set_updated_at();

alter table public.settings enable row level security;
alter table public.coupons enable row level security;

drop policy if exists "public can read settings" on public.settings;
create policy "public can read settings"
on public.settings
for select
to anon, authenticated
using (true);

drop policy if exists "admins can update settings" on public.settings;
create policy "admins can update settings"
on public.settings
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can insert settings" on public.settings;
create policy "admins can insert settings"
on public.settings
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "public can read coupons" on public.coupons;
create policy "public can read coupons"
on public.coupons
for select
to anon, authenticated
using (true);

drop policy if exists "admins can manage coupons" on public.coupons;
create policy "admins can manage coupons"
on public.coupons
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
